name: ardrive_ui_library
description: UI Design Library for the ArDrive Design System

version: 0.0.1

homepage:

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.5

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  percent_indicator: ^4.2.2
  flutter_svg_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Wavehaus
      fonts:
        - asset: assets/fonts/Wavehaus-28Thin.otf
          weight: 300
        - asset: assets/fonts/Wavehaus-42Light.otf
          weight: 400
        - asset: assets/fonts/Wavehaus-66Book.otf
          weight: 500
        - asset: assets/fonts/Wavehaus-95SemiBold.otf
          weight: 600
        - asset: assets/fonts/Wavehaus-128Bold.otf
          weight: 700
        - asset: assets/fonts/Wavehaus-158ExtraBold.otf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
