name: ardrive_uploader
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter
  ardrive_io:
    path: ../ardrive_io
  arweave:
    git:
      url: https://github.com/ardriveapp/arweave-dart.git
      ref: v3.9.0
  ardrive_utils:
    path: ../ardrive_utils
  ardrive_crypto:
    path: ../ardrive_crypto
  arconnect:
    path: ../arconnect
  arfs:
    path: ../arfs
  pst:
    path: ../pst
  uuid: ^4.4.0
  cryptography: ^2.5.0
  rxdart: ^0.27.7
  dio: ^5.4.0
  fpdart: ^1.1.0
  equatable: ^2.0.5
  retry: ^3.1.2
  ardrive_logger:
    path: ../ardrive_logger

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  build_runner: ^2.0.4
  mocktail: ^1.0.2

