name: ardrive_uploader
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter
  ardrive_http:
    git:
      url: https://github.com/ar-io/ardrive_http.git
      ref: v1.3.1
  ardrive_io:
    git:
      url: https://github.com/ar-io/ardrive_io.git
      ref: v1.4.2
  arweave:
    git:
      url: https://github.com/ardriveapp/arweave-dart.git
      ref: v3.8.1
  ardrive_utils:
    path: ../ardrive_utils
  ardrive_crypto:
    path: ../ardrive_crypto
  arconnect:
    path: ../arconnect
  arfs:
    path: ../arfs
  pst:
    path: ../pst
  json_annotation: ^4.8.0
  uuid: ^3.0.4
  system_info_plus: ^0.0.5
  cryptography: ^2.5.0
  rxdart: ^0.27.7
  dio: ^5.3.2
  fpdart: ^1.1.0
  fetch_client:
    git:
      url: https://github.com/thiagocarvalhodev/fetch_client.git
      ref: PE-4754-address-code-review-comments-on-uploader-downloader-implementations
  http: ^1.1.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable:
  build_runner: ^2.0.4
  mocktail: ^0.3.0
