name: ardrive_uploader
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter
  ardrive_http:
    git:
      url: https://github.com/ar-io/ardrive_http.git
      ref: v1.3.1
  ardrive_io:
    git:
      url: https://github.com/ar-io/ardrive_io.git
      ref: PE-4417-export-logs
  arweave:
    path: ../../../arweave-dart
  ardrive_utils:
    path: ../ardrive_utils
  ardrive_crypto:
    path: ../ardrive_crypto
  arconnect:
    path: ../arconnect
  arfs:
    path: ../arfs
  json_annotation: ^4.8.0
  uuid: ^3.0.4
  system_info_plus: ^0.0.5
  cryptography: ^2.5.0
  rxdart: ^0.27.7
  dio: ^5.3.2
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable:
  build_runner: ^2.0.4

